version: 0.0.1-alpha{build}

image: Visual Studio 2017

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

environment:
  test_token_secret: # encrypted test bronto api token secret
    secure: V0qUkR82WOW81seXJ9VCkz63T8x1+WJJgjkpfwdzpT8=

# Ignore testing a commit if only .md files or assets have changed
# Or if various strings are found in the commit message: updated readme, update readme, update docs, update version, update appveyor
skip_commits:
  files:
    - appveyor.yml
    - '**/*.md'
    - assets/**/*

  message: /updated readme.*|update readme.*|update docs.*|update version.*|update appveyor.*/

# There's no need to alter the build number for a Pull Request (PR) since they don't modify anything
pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

cache:
- packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt Wr.UmbFormsBrontoWorkflow.Tests\BrontoSoapTestApiToken.txt.enc -secret %test_token_secret% # decrypt test bronto api token file

before_build:
- cmd: nuget restore Wr.UmbFormsBrontoWorkflow.sln

build:
  publish_nuget: false
  include_nuget_references: false
  verbosity: minimal

after_build:
- ps: >-
    build\tools\UmbracoTools\Wr.UmbracoTools.Packager.exe -set build\umbraco\package_settings.json -out "..\bronto-workflow-umbraco-forms{version}.zip" -ver ${env:APPVEYOR_BUILD_VERSION}

test:
  assemblies:
    only:
    - Wr.UmbFormsBrontoWorkflow.Tests.dll

notifications:
- provider: Slack
  auth_token:
    secure: buvlNNG1gsj/tCAm8nJAqyD8XX2QpkOwHR1xmQCDWhcfHQFKSrejy0lQWS/jhzxRYzsUG2G5A+WMMj+lXdFDHvTJA8aoBwxNXA+N1aoaeG4=
  channel: '#ci-builds'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
